# Generated by Django 5.2.4 on 2025-11-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='number',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='initialInvestment',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='investmentGoal',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='riskTolerance',
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='balance',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cashBalance',
            field=models.FloatField(default=10000.0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockSymbol', models.CharField(max_length=10)),
                ('stockName', models.CharField(max_length=100)),
                ('transactionType', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('pricePerShare', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinSight.portfolio')),
            ],
        ),
    ]
