# Generated by Django 5.2.7 on 2025-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0004_mainuser_country_mainuser_number_portfolio_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='diversification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
