# Generated by Django 5.2.7 on 2025-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0005_portfolio_diversification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('last_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('last_refreshed', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
