# Generated by Django 5.2.7 on 2025-11-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0007_alter_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
