# Generated by Django 5.2.7 on 2025-11-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0008_alter_transaction_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='initialInvestment',
        ),
    ]
