# Generated by Django 5.2.7 on 2025-11-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0009_remove_portfolio_initialinvestment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockPriceCache',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='initialInvestment',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
    ]
