# Generated by Django 5.2.7 on 2025-11-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0010_delete_stockpricecache_portfolio_initialinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='initialInvestment',
        ),
    ]
