# Generated by Django 5.2.7 on 2025-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0011_remove_portfolio_initialinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('last_price', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
