# Generated by Django 5.2.7 on 2025-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinSight', '0012_stockpricecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricecache',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
